# Generated by Django 3.0.8 on 2020-12-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='metric',
        ),
        migrations.AddField(
            model_name='task',
            name='metric',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='task_manager.Metric'),
            preserve_default=False,
        ),
    ]
