# Generated by Django 3.0.8 on 2020-07-26 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.Choice'),
        ),
    ]
