# Generated by Django 3.0.8 on 2020-07-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20200726_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_category', to='task_manager.KRA')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.Metric'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
