# Generated by Django 3.0.8 on 2020-07-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20200726_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='task_manager.KRA'),
        ),
    ]
