# Generated by Django 3.0.8 on 2020-07-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20200726_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='metric',
        ),
        migrations.AddField(
            model_name='task',
            name='metric',
            field=models.ManyToManyField(to='task_manager.Metric'),
        ),
    ]
